CREATE TABLE Orders (
    Id BIGINT IDENTITY (1, 1) CONSTRAINT PK_Orders_Id PRIMARY KEY,
    DeliveryDate DATETIME2(2) NOT NULL,
    Status TINYINT NOT NULL,
    Created DATETIME2(2) NOT NULL CONSTRAINT DF_Orders_Created DEFAULT GETDATE(),
    Updated DATETIME2(2) NOT NULL CONSTRAINT DF_Orders_Updated DEFAULT GETDATE()
);